// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eujzafdofbznzfomqxcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1anphZmRvZmJ6bnpmb21xeGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjM2MTYsImV4cCI6MjA2MjczOTYxNn0.IHz1oWJjUawD38ggi4sBkOiIhexmXu1gds1A95g8l90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);